// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/UniqueIdGenerator.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GenerateResponse struct {
	UniqueId             int64    `protobuf:"varint,1,opt,name=uniqueId,proto3" json:"uniqueId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateResponse) Reset()         { *m = GenerateResponse{} }
func (m *GenerateResponse) String() string { return proto.CompactTextString(m) }
func (*GenerateResponse) ProtoMessage()    {}
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0e2f8a7f31a941e, []int{0}
}

func (m *GenerateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateResponse.Unmarshal(m, b)
}
func (m *GenerateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateResponse.Marshal(b, m, deterministic)
}
func (m *GenerateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateResponse.Merge(m, src)
}
func (m *GenerateResponse) XXX_Size() int {
	return xxx_messageInfo_GenerateResponse.Size(m)
}
func (m *GenerateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateResponse proto.InternalMessageInfo

func (m *GenerateResponse) GetUniqueId() int64 {
	if m != nil {
		return m.UniqueId
	}
	return 0
}

type GenerateRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GenerateRequest) Reset()         { *m = GenerateRequest{} }
func (m *GenerateRequest) String() string { return proto.CompactTextString(m) }
func (*GenerateRequest) ProtoMessage()    {}
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a0e2f8a7f31a941e, []int{1}
}

func (m *GenerateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GenerateRequest.Unmarshal(m, b)
}
func (m *GenerateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GenerateRequest.Marshal(b, m, deterministic)
}
func (m *GenerateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenerateRequest.Merge(m, src)
}
func (m *GenerateRequest) XXX_Size() int {
	return xxx_messageInfo_GenerateRequest.Size(m)
}
func (m *GenerateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GenerateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GenerateRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GenerateResponse)(nil), "GenerateResponse")
	proto.RegisterType((*GenerateRequest)(nil), "GenerateRequest")
}

func init() {
	proto.RegisterFile("proto/UniqueIdGenerator.proto", fileDescriptor_a0e2f8a7f31a941e)
}

var fileDescriptor_a0e2f8a7f31a941e = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x0f, 0xcd, 0xcb, 0x2c, 0x2c, 0x4d, 0xf5, 0x4c, 0x71, 0x4f, 0xcd, 0x4b, 0x2d, 0x4a,
	0x2c, 0xc9, 0x2f, 0xd2, 0x03, 0x8b, 0x2b, 0xe9, 0x71, 0x09, 0x40, 0x85, 0x52, 0x83, 0x52, 0x8b,
	0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0xa4, 0xb8, 0x38, 0x4a, 0xa1, 0xca, 0x25, 0x18, 0x15, 0x18,
	0x35, 0x98, 0x83, 0xe0, 0x7c, 0x25, 0x41, 0x2e, 0x7e, 0x84, 0xfa, 0xc2, 0xd2, 0xd4, 0xe2, 0x12,
	0x23, 0x17, 0x2e, 0x41, 0x0c, 0xd3, 0x85, 0xf4, 0xb9, 0x38, 0x60, 0xea, 0x84, 0x04, 0xf4, 0xd0,
	0xb4, 0x48, 0x09, 0xea, 0xa1, 0x5b, 0xea, 0xc4, 0x16, 0xc5, 0xa2, 0x9f, 0x58, 0x90, 0x99, 0xc4,
	0x06, 0x76, 0x97, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x3b, 0xe6, 0xf2, 0xb8, 0x00, 0x00,
	0x00,
}
